version: '3'

services:
  otras:
    build: ./microservicios/otras
    depends_on:
      - db_otras
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://db_otras:27017/test
  db_otras:
    image: mongo:4.4.6

  estudiante:
    build: ./microservicios/estudiante
    depends_on:
      - db_estudiante
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://db_estudiante:27017/test
  db_usuarios:
    image: mongo:4.4.6

  nginx:
    image: nginx:latest
    ports: ["8080:8080"]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - otras
      - estudiante
